# Install Node dependencies and build app

name: Build Node.js

on:
  pull_request:
    branches: [ master, prod ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Build node app
      working-directory: ./overview
      env:
        CI: true
      run: |
        npm ci
        npm run generate --fail-on-error

